### ISSUE TITLE
JS lifecycle

### ISSUE THREAD

**Issue by federicomichela** [uzoway/montar-landing-page#5]
There's a few things to note here:

- your js at the moment works because you've added the script tag at the end of the html. This ensures that the DOM has already been loaded and that is why your js file works although it's not ideal.

I'd suggest you review what DOM lifecycle events are, and refactor your js file to act upon a DOM lifecycle hook :)
([reference article](https://javascript.info/onload-ondomcontentloaded))

- be careful on line 9 of main.js where you do the following:
`const openMobileNav = document.getElementById("mobile").addEventListener("click", () => {`
addEventListener returns undefined hence your openMobileNav is undefined.
You're not actually using that constant so you could remove it all together or for consistency with the previous constants you can assign it just the document.getElementById...

e.g.
`const openMobileNav = document.getElementById("mobile");

openMobileNav.addEventListener(...)
`

- finally, while it's nice to see you're trying to fix colours by applying filters, I'm not so sure that the approach  you use to  toggle the 2 menus is ideal.
Personally I would do everything via css or by toggling classes.

**Comment by uzoway** [comment]
After reading the reference article on DOM lifecycle hooks, I decided to add the "defer" attribute on the script tag to prevent the DOM from having to execute the script tag before completely loading the DOM.
